services:

  rabbitmq:
    image: rabbitmq:4.3.0-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-user:
    image: mongodb/mongodb-community-server:latest-slim
    container_name: mongo-user
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: user-service

  mongo-car:
    image: mongodb/mongodb-community-server:latest-slim
    container_name: mongo-car
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: car-service

  mongo-booking:
    image: mongodb/mongodb-community-server:latest-slim
    container_name: mongo-booking
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: booking-service

  booking-service:
    build:
      context: .
      dockerfile: booking-service/Dockerfile
    container_name: booking-service
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MONGO_HOST: mongo-booking
      MONGO_PORT: 27017
      MONGO_DB: booking-service
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      JWT_SECRET: changeme
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo-booking:
        condition: service_started
