services:
  rabbitmq:
    image: rabbitmq:4.3.0-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-user:
    image: mongodb/mongodb-community-server:latest-slim
    container_name: mongo-user
    environment:
      MONGO_INITDB_DATABASE: user-service
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongo-user-data:/data/db

  mongo-car:
    image: mongodb/mongodb-community-server:latest-slim
    container_name: mongo-car
    environment:
      MONGO_INITDB_DATABASE: car-service
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongo-car-data:/data/db

  mongo-booking:
    image: mongodb/mongodb-community-server:latest-slim
    container_name: mongo-booking
    environment:
      MONGO_INITDB_DATABASE: booking-service
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongo-booking-data:/data/db

  booking-service:
    image: ghcr.io/michael-mezgo/hcw-se-backend-2/booking-service:latest
    container_name: booking-service
    environment:
      PORT: 8080
      MONGO_HOST: mongo-booking
      MONGO_USER: admin
      MONGO_PASSWORD: secretpassword
      MONGO_PORT: 27017
      MONGO_DB: booking-service
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      JWT_SECRET: changeme
      JWT_ISSUER: APP
      JWT_AUDIENCE: APP
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo-booking:
        condition: service_started
  
  car-service:
    image: ghcr.io/michael-mezgo/hcw-se-backend-2/car-service:latest
    container_name: car-service
    environment:
      PORT: 8080
      MONGO_HOST: mongo-car
      MONGO_USER: admin
      MONGO_PASSWORD: secretpassword
      MONGO_PORT: 27017
      MONGO_DB: car-service
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      JWT_SECRET: changeme
      JWT_ISSUER: APP
      JWT_AUDIENCE: APP
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo-car:
        condition: service_started

  user-service:
    image: ghcr.io/michael-mezgo/hcw-se-backend-2/user-service:latest
    container_name: user-service
    environment:
      PORT: 8080
      MONGO_HOST: mongo-user
      MONGO_USER: admin
      MONGO_PASSWORD: secretpassword
      MONGO_PORT: 27017
      MONGO_DB: user-service
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      JWT_SECRET: changeme
      JWT_ISSUER: APP
      JWT_AUDIENCE: APP
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo-user:
        condition: service_started
  
  frontend:
    image: ghcr.io/michael-mezgo/hcw-se-frontend-2:latest
    container_name: frontend
    ports:
      - "80:80"