ktor:
  deployment:
    port: 8080
  application:
    modules:
      - at.ac.hcw.HttpKt.configureHttp
      - at.ac.hcw.SerializationKt.configureSerialization
      - at.ac.hcw.SecurityKt.configureSecurity
      - at.ac.hcw.MongoKt.configureMongo
      - at.ac.hcw.RabbitmqKt.configureRabbitmq
      - at.ac.hcw.ResourcesKt.configureResources
      - at.ac.hcw.RoutingKt.configureRouting
      - at.ac.hcw.OpenApiKt.configureOpenApi
      - at.ac.hcw.GrpcKt.configureGrpc

db:
  mongo:
    host: localhost
    port: 27018
    database:
        name: car-service

grpc:
  currency:
    host: localhost
    port: 5125

rabbitmq:
  uri: amqp://guest:guest@localhost:5672
