ktor:
  deployment:
    port: $PORT
  application:
    modules:
      - at.ac.hcw.HttpKt.configureHttp
      - at.ac.hcw.SerializationKt.configureSerialization
      - at.ac.hcw.SecurityKt.configureSecurity
      - at.ac.hcw.MongoKt.configureMongo
      - at.ac.hcw.RabbitmqKt.configureRabbitmq
      - at.ac.hcw.GrpcKt.configureGrpc
      - at.ac.hcw.ResourcesKt.configureResources
      - at.ac.hcw.BlobStorageKt.configureBlobStorage
      - at.ac.hcw.RoutingKt.configureRouting
      - at.ac.hcw.OpenApiKt.configureOpenApi

db:
  mongo:
    host: $MONGO_HOST
    port: $MONGO_PORT
    database:
        name: $MONGO_DB

grpc:
  currency:
    host: $GRPC_HOST
    port: $GRPC_PORT
    apiKey: $GRPC_API_KEY

rabbitmq:
  uri: $RABBITMQ_URI

blob:
  storage:
    connectionString: $BLOB_CONNECTION_STRING
    containerName: $BLOB_CONTAINER_NAME
