ktor:
  deployment:
    port: 8080
  application:
    modules:
      - at.ac.hcw.HttpKt.configureHttp
      - at.ac.hcw.SerializationKt.configureSerialization
      - at.ac.hcw.security.JwtValidatorKt.configureSecurity
      - at.ac.hcw.MongoKt.configureMongo
      #- at.ac.hcw.RabbitmqKt.configureRabbitmq
      - at.ac.hcw.ResourcesKt.configureResources
      - at.ac.hcw.RoutingKt.configureRouting
      - at.ac.hcw.OpenApiKt.configureOpenApi

db:
  mongo:
    host: localhost
    port: 27017
    database:
      name: user-service

rabbitmq:
  uri: amqp://guest:guest@localhost:5672
